# Generated by Django 5.1.6 on 2025-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=50)),
                ('company_about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('NonIT', 'NonIT'), ('Mobiles', 'Mobiles')], max_length=100)),
                ('added', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
