# Generated by Django 5.1.6 on 2025-02-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_phone', models.CharField(max_length=10)),
                ('employee_about', models.TextField()),
                ('employee_position', models.CharField(choices=[('Manager', 'manager'), ('HR', 'HR'), ('Software Developer', 'Software Developer'), ('Team Lead', 'Team Lead')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
